# ANALYSIS OF snoverATAC-seq sample RL3295 - peaks called with MACS2 NFR peaks within same sample

## Pre-processing

In [1]:
import numpy as np
import pandas as pd
import scanpy as sc
import anndata as ad
import matplotlib.pyplot as plt
import seaborn as sns
import episcanpy.api as epi
from os import listdir

In [2]:
sc.settings.verbosity = 3 # shows errors (0), warnings (1), info (2), hints (3), progress (4) - 4 useful for debugging
sc.logging.print_header()
sc.settings.set_figure_params(dpi=80,facecolor='None')
sns.set_context('paper')

 TqdmWarning:/home/dmakosa/working_data_01/apps/miniconda3/envs/snRNAseq/lib/python3.7/site-packages/tqdm/auto.py:22: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html

scanpy==1.9.1 anndata==0.8.0 umap==0.5.3 numpy==1.21.6 scipy==1.7.3 pandas==1.3.5 scikit-learn==1.0.2 statsmodels==0.13.2 python-igraph==0.9.10 pynndescent==0.5.6

## Load the data

In [3]:
cellranger_path = '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/'

In [4]:
samples = listdir(cellranger_path)

In [5]:
samples

['RL3295_21_dirty_THS_37_shortREV_highTn5',
 'RL3295_39_dirty_THS_30_blockedREV_highTn5',
 'RL3295_40_dirty_OMNI_30_blockedREV_lowTn5',
 'RL3295_23_dirty_OMNI_37_shortREV_mediumTn5',
 'RL3295_25_dirty_THS_30_blockedREV_lowTn5',
 'RL3295_72_sucrose_OMNI_37_shortREV_highTn5',
 'RL3295_60_sucrose_OMNI_37_shortREV_highTn5',
 'RL3295_33_dirty_THS_37_blockedREV_highTn5',
 'RL3295_36_dirty_OMNI_37_blockedREV_highTn5',
 'RL3295_94_sucrose_OMNI_37_blockedREV_lowTn5',
 'RL3295_77_sucrose_OMNI_30_blockedREV_mediumTn5',
 'RL3295_57_sucrose_THS_37_shortREV_highTn5',
 'RL3295_27_dirty_THS_30_blockedREV_highTn5',
 'RL3295_38_dirty_THS_30_blockedREV_mediumTn5',
 'RL3295_76_sucrose_OMNI_30_blockedREV_lowTn5',
 'RL3295_42_dirty_OMNI_30_blockedREV_highTn5',
 'RL3295_34_dirty_OMNI_37_blockedREV_lowTn5',
 'RL3295_06_dirty_OMNI_30_shortREV_highTn5',
 'RL3295_07_dirty_THS_37_shortREV_lowTn5',
 'RL3295_08_dirty_THS_37_shortREV_mediumTn5',
 'RL3295_10_dirty_OMNI_37_shortREV_lowTn5',
 'RL3295_09_dirty_THS_37_shortREV_highTn5',
 'RL3295_02_dirty_THS_30_shortREV_mediumTn5',
 'RL3295_16_dirty_OMNI_30_shortREV_lowTn5',
 'RL3295_05_dirty_OMNI_30_shortREV_mediumTn5',
 'RL3295_19_dirty_THS_37_shortREV_lowTn5',
 'RL3295_01_dirty_THS_30_shortREV_lowTn5',
 'RL3295_14_dirty_THS_30_shortREV_mediumTn5',
 'RL3295_13_dirty_THS_30_shortREV_lowTn5',
 'RL3295_18_dirty_OMNI_30_shortREV_highTn5',
 'RL3295_15_dirty_THS_30_shortREV_highTn5',
 'RL3295_04_dirty_OMNI_30_shortREV_lowTn5',
 'RL3295_17_dirty_OMNI_30_shortREV_mediumTn5',
 'RL3295_03_dirty_THS_30_shortREV_highTn5',
 'RL3295_12_dirty_OMNI_37_shortREV_highTn5',
 'RL3295_11_dirty_OMNI_37_shortREV_mediumTn5',
 'RL3295_35_dirty_OMNI_37_blockedREV_mediumTn5',
 'RL3295_41_dirty_OMNI_30_blockedREV_mediumTn5',
 'RL3295_56_sucrose_THS_37_shortREV_mediumTn5',
 'RL3295_75_sucrose_THS_30_blockedREV_highTn5',
 'RL3295_37_dirty_THS_30_blockedREV_lowTn5',
 'RL3295_20_dirty_THS_37_shortREV_mediumTn5',
 'RL3295_53_sucrose_OMNI_30_shortREV_mediumTn5',
 'RL3295_95_sucrose_OMNI_37_blockedREV_mediumTn5',
 'RL3295_22_dirty_OMNI_37_shortREV_lowTn5',
 'RL3295_24_dirty_OMNI_37_shortREV_highTn5',
 'RL3295_30_dirty_OMNI_30_blockedREV_highTn5',
 'RL3295_28_dirty_OMNI_30_blockedREV_lowTn5',
 'RL3295_48_dirty_OMNI_37_blockedREV_highTn5',
 'RL3295_32_dirty_THS_37_blockedREV_mediumTn5',
 'RL3295_26_dirty_THS_30_blockedREV_mediumTn5',
 'RL3295_47_dirty_OMNI_37_blockedREV_mediumTn5',
 'RL3295_58_sucrose_OMNI_37_shortREV_lowTn5',
 'RL3295_43_dirty_THS_37_blockedREV_lowTn5',
 'RL3295_29_dirty_OMNI_30_blockedREV_mediumTn5',
 'RL3295_31_dirty_THS_37_blockedREV_lowTn5',
 'RL3295_49_sucrose_THS_30_shortREV_lowTn5',
 'RL3295_63_sucrose_THS_30_shortREV_highTn5',
 'RL3295_50_sucrose_THS_30_shortREV_mediumTn5',
 'RL3295_44_dirty_THS_37_blockedREV_mediumTn5',
 'RL3295_59_sucrose_OMNI_37_shortREV_mediumTn5',
 'RL3295_45_dirty_THS_37_blockedREV_highTn5',
 'RL3295_64_sucrose_OMNI_30_shortREV_lowTn5',
 'RL3295_46_dirty_OMNI_37_blockedREV_lowTn5',
 'RL3295_51_sucrose_THS_30_shortREV_highTn5',
 'RL3295_52_sucrose_OMNI_30_shortREV_lowTn5',
 'RL3295_54_sucrose_OMNI_30_shortREV_highTn5',
 'RL3295_55_sucrose_THS_37_shortREV_lowTn5',
 'RL3295_61_sucrose_THS_30_shortREV_lowTn5',
 'RL3295_62_sucrose_THS_30_shortREV_mediumTn5',
 'RL3295_87_sucrose_THS_30_blockedREV_highTn5',
 'RL3295_90_sucrose_OMNI_30_blockedREV_highTn5',
 'RL3295_91_sucrose_THS_37_blockedREV_lowTn5',
 'RL3295_92_sucrose_THS_37_blockedREV_mediumTn5',
 'RL3295_93_sucrose_THS_37_blockedREV_highTn5',
 'RL3295_96_sucrose_OMNI_37_blockedREV_highTn5',
 'RL3295_65_sucrose_OMNI_30_shortREV_mediumTn5',
 'RL3295_67_sucrose_THS_37_shortREV_lowTn5',
 'RL3295_66_sucrose_OMNI_30_shortREV_highTn5',
 'RL3295_68_sucrose_THS_37_shortREV_mediumTn5',
 'RL3295_69_sucrose_THS_37_shortREV_highTn5',
 'RL3295_70_sucrose_OMNI_37_shortREV_lowTn5',
 'RL3295_71_sucrose_OMNI_37_shortREV_mediumTn5',
 'RL3295_73_sucrose_THS_30_blockedREV_lowTn5',
 'RL3295_74_sucrose_THS_30_blockedREV_mediumTn5',
 'RL3295_78_sucrose_OMNI_30_blockedREV_highTn5',
 'RL3295_79_sucrose_THS_37_blockedREV_lowTn5',
 'RL3295_80_sucrose_THS_37_blockedREV_mediumTn5',
 'RL3295_81_sucrose_THS_37_blockedREV_highTn5',
 'RL3295_82_sucrose_OMNI_37_blockedREV_lowTn5',
 'RL3295_83_sucrose_OMNI_37_blockedREV_mediumTn5',
 'RL3295_84_sucrose_OMNI_37_blockedREV_highTn5',
 'RL3295_85_sucrose_THS_30_blockedREV_lowTn5',
 'RL3295_86_sucrose_THS_30_blockedREV_mediumTn5',
 'RL3295_88_sucrose_OMNI_30_blockedREV_lowTn5',
 'RL3295_89_sucrose_OMNI_30_blockedREV_mediumTn5']

In [6]:
filepaths = [cellranger_path + sample + '/outs/raw_peak_bc_matrix.h5' for sample in samples]
matrixpaths = [cellranger_path + sample + '/outs/raw_peak_bc_matrix/matrix.mtx' for sample in samples]
cellpaths = [cellranger_path + sample + '/outs/raw_peak_bc_matrix/barcodes.tsv' for sample in samples]
featurepaths = [cellranger_path + sample + '/outs/raw_peak_bc_matrix/peaks.bed' for sample in samples]

In [7]:
filepaths

['/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_21_dirty_THS_37_shortREV_highTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_39_dirty_THS_30_blockedREV_highTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_40_dirty_OMNI_30_blockedREV_lowTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_23_dirty_OMNI_37_shortREV_mediumTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_25_dirty_THS_30_blockedREV_lowTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_72_sucrose_OMNI_37_shortREV_highTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_60_sucrose_OMNI_37_shortREV_highTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_33_dirty_THS_37_blockedREV_highTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_36_dirty_OMNI_37_blockedREV_highTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_94_sucrose_OMNI_37_blockedREV_lowTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_77_sucrose_OMNI_30_blockedREV_mediumTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_57_sucrose_THS_37_shortREV_highTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_27_dirty_THS_30_blockedREV_highTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_38_dirty_THS_30_blockedREV_mediumTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_76_sucrose_OMNI_30_blockedREV_lowTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_42_dirty_OMNI_30_blockedREV_highTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_34_dirty_OMNI_37_blockedREV_lowTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_06_dirty_OMNI_30_shortREV_highTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_07_dirty_THS_37_shortREV_lowTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_08_dirty_THS_37_shortREV_mediumTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_10_dirty_OMNI_37_shortREV_lowTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_09_dirty_THS_37_shortREV_highTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_02_dirty_THS_30_shortREV_mediumTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_16_dirty_OMNI_30_shortREV_lowTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_05_dirty_OMNI_30_shortREV_mediumTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_19_dirty_THS_37_shortREV_lowTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_01_dirty_THS_30_shortREV_lowTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_14_dirty_THS_30_shortREV_mediumTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_13_dirty_THS_30_shortREV_lowTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_18_dirty_OMNI_30_shortREV_highTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_15_dirty_THS_30_shortREV_highTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_04_dirty_OMNI_30_shortREV_lowTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_17_dirty_OMNI_30_shortREV_mediumTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_03_dirty_THS_30_shortREV_highTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_12_dirty_OMNI_37_shortREV_highTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_11_dirty_OMNI_37_shortREV_mediumTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_35_dirty_OMNI_37_blockedREV_mediumTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_41_dirty_OMNI_30_blockedREV_mediumTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_56_sucrose_THS_37_shortREV_mediumTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_75_sucrose_THS_30_blockedREV_highTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_37_dirty_THS_30_blockedREV_lowTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_20_dirty_THS_37_shortREV_mediumTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_53_sucrose_OMNI_30_shortREV_mediumTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_95_sucrose_OMNI_37_blockedREV_mediumTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_22_dirty_OMNI_37_shortREV_lowTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_24_dirty_OMNI_37_shortREV_highTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_30_dirty_OMNI_30_blockedREV_highTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_28_dirty_OMNI_30_blockedREV_lowTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_48_dirty_OMNI_37_blockedREV_highTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_32_dirty_THS_37_blockedREV_mediumTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_26_dirty_THS_30_blockedREV_mediumTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_47_dirty_OMNI_37_blockedREV_mediumTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_58_sucrose_OMNI_37_shortREV_lowTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_43_dirty_THS_37_blockedREV_lowTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_29_dirty_OMNI_30_blockedREV_mediumTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_31_dirty_THS_37_blockedREV_lowTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_49_sucrose_THS_30_shortREV_lowTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_63_sucrose_THS_30_shortREV_highTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_50_sucrose_THS_30_shortREV_mediumTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_44_dirty_THS_37_blockedREV_mediumTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_59_sucrose_OMNI_37_shortREV_mediumTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_45_dirty_THS_37_blockedREV_highTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_64_sucrose_OMNI_30_shortREV_lowTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_46_dirty_OMNI_37_blockedREV_lowTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_51_sucrose_THS_30_shortREV_highTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_52_sucrose_OMNI_30_shortREV_lowTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_54_sucrose_OMNI_30_shortREV_highTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_55_sucrose_THS_37_shortREV_lowTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_61_sucrose_THS_30_shortREV_lowTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_62_sucrose_THS_30_shortREV_mediumTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_87_sucrose_THS_30_blockedREV_highTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_90_sucrose_OMNI_30_blockedREV_highTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_91_sucrose_THS_37_blockedREV_lowTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_92_sucrose_THS_37_blockedREV_mediumTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_93_sucrose_THS_37_blockedREV_highTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_96_sucrose_OMNI_37_blockedREV_highTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_65_sucrose_OMNI_30_shortREV_mediumTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_67_sucrose_THS_37_shortREV_lowTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_66_sucrose_OMNI_30_shortREV_highTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_68_sucrose_THS_37_shortREV_mediumTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_69_sucrose_THS_37_shortREV_highTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_70_sucrose_OMNI_37_shortREV_lowTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_71_sucrose_OMNI_37_shortREV_mediumTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_73_sucrose_THS_30_blockedREV_lowTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_74_sucrose_THS_30_blockedREV_mediumTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_78_sucrose_OMNI_30_blockedREV_highTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_79_sucrose_THS_37_blockedREV_lowTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_80_sucrose_THS_37_blockedREV_mediumTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_81_sucrose_THS_37_blockedREV_highTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_82_sucrose_OMNI_37_blockedREV_lowTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_83_sucrose_OMNI_37_blockedREV_mediumTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_84_sucrose_OMNI_37_blockedREV_highTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_85_sucrose_THS_30_blockedREV_lowTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_86_sucrose_THS_30_blockedREV_mediumTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_88_sucrose_OMNI_30_blockedREV_lowTn5/outs/raw_peak_bc_matrix.h5',
 '/home/dmakosa/working_data_02/snoverATAC/RL3294_RL3295/RL3295_cellrangerOnMACS2peaks/RL3295_89_sucrose_OMNI_30_blockedREV_mediumTn5/outs/raw_peak_bc_matrix.h5']

In [8]:
sampleRL = [sample.split("_")[0] for sample in samples]
sampleWell = [sample.split("_")[1] for sample in samples]
samplePurity = [sample.split("_")[2] for sample in samples]
sampleTagBuffer = [sample.split("_")[3] for sample in samples]
sampleTagTemp = [sample.split("_")[4] for sample in samples]
sampleMErev = [sample.split("_")[5] for sample in samples]
sampleTn5conc = [sample.split("_")[6] for sample in samples]

In [9]:
import copy
adatas = copy.deepcopy(samples)
for i,item in enumerate(matrixpaths):
    adatas[i] = epi.pp.read_ATAC_10x(matrixpaths[i], cell_names = cellpaths[i], var_names = featurepaths[i])

 FutureWarning:/home/dmakosa/working_data_01/apps/miniconda3/envs/snRNAseq/lib/python3.7/site-packages/episcanpy/preprocessing/_load_matrix.py:39: X.dtype being converted to np.float32 from int64. In the next version of anndata (0.9) conversion will not be automatic. Pass dtype explicitly to avoid this warning. Pass `AnnData(X, dtype=X.dtype, ...)` to get the future behavour.

In [10]:
[item.shape for item in adatas]

[(95151, 307084),
 (94615, 307084),
 (76432, 307084),
 (87633, 307084),
 (76499, 307084),
 (78811, 307084),
 (79568, 307084),
 (113255, 307084),
 (119609, 307084),
 (71341, 307084),
 (64413, 307084),
 (87018, 307084),
 (105162, 307084),
 (94204, 307084),
 (57189, 307084),
 (93389, 307084),
 (69091, 307084),
 (97380, 307084),
 (64281, 307084),
 (69866, 307084),
 (72476, 307084),
 (77516, 307084),
 (78024, 307084),
 (47754, 307084),
 (96266, 307084),
 (47558, 307084),
 (55852, 307084),
 (67170, 307084),
 (57018, 307084),
 (68984, 307084),
 (84476, 307084),
 (52496, 307084),
 (78280, 307084),
 (76100, 307084),
 (93479, 307084),
 (71355, 307084),
 (102002, 307084),
 (108716, 307084),
 (25731, 307084),
 (70290, 307084),
 (61688, 307084),
 (78536, 307084),
 (74413, 307084),
 (77592, 307084),
 (51122, 307084),
 (83160, 307084),
 (83098, 307084),
 (83747, 307084),
 (99994, 307084),
 (108578, 307084),
 (82542, 307084),
 (98824, 307084),
 (37475, 307084),
 (81995, 307084),
 (107208, 307084),
 (76691, 307084),
 (39019, 307084),
 (62692, 307084),
 (53295, 307084),
 (102355, 307084),
 (64289, 307084),
 (115044, 307084),
 (26700, 307084),
 (88240, 307084),
 (64021, 307084),
 (32062, 307084),
 (54858, 307084),
 (65644, 307084),
 (43010, 307084),
 (52709, 307084),
 (93445, 307084),
 (75919, 307084),
 (69088, 307084),
 (91462, 307084),
 (85987, 307084),
 (52300, 307084),
 (64784, 307084),
 (57990, 307084),
 (59686, 307084),
 (84604, 307084),
 (86301, 307084),
 (52770, 307084),
 (66183, 307084),
 (52233, 307084),
 (78456, 307084),
 (78780, 307084),
 (82500, 307084),
 (80592, 307084),
 (102377, 307084),
 (61740, 307084),
 (84798, 307084),
 (68052, 307084),
 (68505, 307084),
 (106372, 307084),
 (63946, 307084),
 (66140, 307084)]

In [11]:
adatas[1].var

Empty DataFrame
Columns: []
Index: [GRCh38_chr1_10012_10657, GRCh38_chr1_10915_11235, GRCh38_chr1_19184_19343, GRCh38_chr1_20870_21114, GRCh38_chr1_26013_26174, GRCh38_chr1_28636_29089, GRCh38_chr1_29259_29454, GRCh38_chr1_29563_29908, GRCh38_chr1_29949_30145, GRCh38_chr1_34657_35067, GRCh38_chr1_91303_91552, GRCh38_chr1_178679_179075, GRCh38_chr1_179167_179438, GRCh38_chr1_180749_181048, GRCh38_chr1_181701_182016, GRCh38_chr1_190163_190621, GRCh38_chr1_191305_191812, GRCh38_chr1_199209_200632, GRCh38_chr1_205178_205670, GRCh38_chr1_206399_206796, GRCh38_chr1_266622_266844, GRCh38_chr1_267771_268159, GRCh38_chr1_292266_292455, GRCh38_chr1_297157_297404, GRCh38_chr1_348049_348322, GRCh38_chr1_348978_349208, GRCh38_chr1_350855_351666, GRCh38_chr1_351754_351911, GRCh38_chr1_376990_377457, GRCh38_chr1_477854_478130, GRCh38_chr1_478498_478712, GRCh38_chr1_479510_479787, GRCh38_chr1_486984_487177, GRCh38_chr1_493799_493984, GRCh38_chr1_494224_494654, GRCh38_chr1_499555_499898, GRCh38_chr1_505324_505475, GRCh38_chr1_509911_510078, GRCh38_chr1_529157_529440, GRCh38_chr1_529978_530145, GRCh38_chr1_530770_530948, GRCh38_chr1_531341_531577, GRCh38_chr1_533567_533751, GRCh38_chr1_535077_535242, GRCh38_chr1_586042_586301, GRCh38_chr1_587755_588032, GRCh38_chr1_593729_594054, GRCh38_chr1_598431_598600, GRCh38_chr1_604440_604607, GRCh38_chr1_605074_605677, GRCh38_chr1_605755_606693, GRCh38_chr1_610981_611131, GRCh38_chr1_615732_615928, GRCh38_chr1_624034_624184, GRCh38_chr1_629099_630038, GRCh38_chr1_630199_630483, GRCh38_chr1_630723_631377, GRCh38_chr1_631809_632999, GRCh38_chr1_633405_633586, GRCh38_chr1_633721_634906, GRCh38_chr1_657334_657598, GRCh38_chr1_665921_666103, GRCh38_chr1_666659_667159, GRCh38_chr1_674857_675055, GRCh38_chr1_684656_684898, GRCh38_chr1_699160_699310, GRCh38_chr1_699553_699713, GRCh38_chr1_730681_730884, GRCh38_chr1_731196_731353, GRCh38_chr1_732021_732212, GRCh38_chr1_778031_778234, GRCh38_chr1_778293_779296, GRCh38_chr1_779358_780094, GRCh38_chr1_789831_789992, GRCh38_chr1_817321_817499, GRCh38_chr1_817943_818149, GRCh38_chr1_826745_828103, GRCh38_chr1_850310_850644, GRCh38_chr1_858783_859017, GRCh38_chr1_869686_870228, GRCh38_chr1_903781_904193, GRCh38_chr1_904289_904937, GRCh38_chr1_921127_921379, GRCh38_chr1_923696_924047, GRCh38_chr1_940150_940572, GRCh38_chr1_958849_959950, GRCh38_chr1_960435_960655, GRCh38_chr1_975975_976364, GRCh38_chr1_984052_984544, GRCh38_chr1_999963_1000983, GRCh38_chr1_1001854_1002085, GRCh38_chr1_1013230_1014475, GRCh38_chr1_1019211_1019763, GRCh38_chr1_1020045_1020427, GRCh38_chr1_1025049_1025329, GRCh38_chr1_1032490_1032744, GRCh38_chr1_1032910_1033385, GRCh38_chr1_1040595_1041073, GRCh38_chr1_1050839_1051045, GRCh38_chr1_1058847_1059884, ...]

[307084 rows x 0 columns]

In [12]:
for i,item in enumerate(adatas):
    adatas[i].obs['Sample'] = samples[i]
    adatas[i].obs['RL'] = sampleRL[i] 
    adatas[i].obs['Well'] = sampleWell[i] 
    adatas[i].obs['Purity'] = samplePurity[i] 
    adatas[i].obs['TagBuffer'] = sampleTagBuffer[i] 
    adatas[i].obs['TagTemp'] = sampleTagTemp[i] 
    adatas[i].obs['MErev'] = sampleMErev[i] 
    adatas[i].obs['Tn5conc'] = sampleTn5conc[i]

In [13]:
adatas[1].obs

,Sample,RL,Well,Purity,TagBuffer,TagTemp,MErev,Tn5conc
AAACGAAAGAACTAAC-1,RL3295_39_dirty_THS_30_blockedREV_highTn5,RL3295,39,dirty,THS,30,blockedREV,highTn5
AAACGAAAGAAGCCTG-1,RL3295_39_dirty_THS_30_blockedREV_highTn5,RL3295,39,dirty,THS,30,blockedREV,highTn5
AAACGAAAGACAGCTG-1,RL3295_39_dirty_THS_30_blockedREV_highTn5,RL3295,39,dirty,THS,30,blockedREV,highTn5
AAACGAAAGAGAGTAG-1,RL3295_39_dirty_THS_30_blockedREV_highTn5,RL3295,39,dirty,THS,30,blockedREV,highTn5
AAACGAAAGAGCCACA-1,RL3295_39_dirty_THS_30_blockedREV_highTn5,RL3295,39,dirty,THS,30,blockedREV,highTn5
...,...,...,...,...,...,...,...,...
TTTGTGTTCTCTGACC-1,RL3295_39_dirty_THS_30_blockedREV_highTn5,RL3295,39,dirty,THS,30,blockedREV,highTn5
TTTGTGTTCTCTTCTC-1,RL3295_39_dirty_THS_30_blockedREV_highTn5,RL3295,39,dirty,THS,30,blockedREV,highTn5
TTTGTGTTCTGGCTAA-1,RL3295_39_dirty_THS_30_blockedREV_highTn5,RL3295,39,dirty,THS,30,blockedREV,highTn5
TTTGTGTTCTGTGTCC-1,RL3295_39_dirty_THS_30_blockedREV_highTn5,RL3295,39,dirty,THS,30,blockedREV,highTn5
TTTGTGTTCTTGTGCC-1,RL3295_39_dirty_THS_30_blockedREV_highTn5,RL3295,39,dirty,THS,30,blockedREV,highTn5

In [14]:
# check this one first (merge = same?? for ATAC?)
adatas_all = ad.concat([item for item in adatas], merge = 'same', index_unique='_')
adatas_all

AnnData object with n_obs × n_vars = 7212061 × 307084
    obs: 'Sample', 'RL', 'Well', 'Purity', 'TagBuffer', 'TagTemp', 'MErev', 'Tn5conc'

In [15]:
adatas_all.var_names

Index(['GRCh38_chr1_10012_10657', 'GRCh38_chr1_10915_11235',
       'GRCh38_chr1_19184_19343', 'GRCh38_chr1_20870_21114',
       'GRCh38_chr1_26013_26174', 'GRCh38_chr1_28636_29089',
       'GRCh38_chr1_29259_29454', 'GRCh38_chr1_29563_29908',
       'GRCh38_chr1_29949_30145', 'GRCh38_chr1_34657_35067',
       ...
       'mm10_chrY_90812243_90812718', 'mm10_chrY_90812809_90813257',
       'mm10_chrY_90818244_90818581', 'mm10_chrY_90818741_90818960',
       'mm10_chrY_90819112_90819389', 'mm10_chrY_90819540_90819845',
       'mm10_chrY_90824173_90824421', 'mm10_chrY_90825257_90825564',
       'mm10_chrY_90841656_90841860', 'mm10_chrY_90842850_90843020'],
      dtype='object', length=307084)